# config/nsf_neural.yaml

name: "reinforcement learning"

sources:
  agency:
    - "nsf"
    - "nih"
  keywords:
    - "reinforcement learning"
    - "deep reinforcement learning"
    - "multi-agent reinforcement learning"
    - "inverse reinforcement learning"
    - "Markov decision process"
    - "policy gradient"
  date_from: "01/01/2000"
  date_to: ""
  max_results: 30
